server:
  port: ${PORT:9092}
  servlet:
    context-path: /

salesforce:
  instance:
    apiVersion: ${SALESFORCE_API_VERSION:v48.0}
    instanceId: ${SALESFORCE_INSTANCE_ID}

  oauth:
    clientId: ${SALESFORCE_CLIENT_ID}
    clientSecret: ${SALESFORCE_CLIENT_SECRET}
    username: ${SALESFORCE_USERNAME}
    password: ${SALESFORCE_PASSWORD}
  
  keystore:
    path: ${KEYSTORE_PATH:classpath:keystore/keystore.jks}
    password: ${KEYSTORE_PASSWORD:ottimizza@123}